import { z } from "zod";
export const BrandBriefInputSchema = z.object({
  nameAr: z.string().min(1),
  nameEn: z.string().optional(),
  spelling: z.string().optional(),
  currentSlogan: z.string().optional(),
  description: z.string().min(10),
  sector: z.string().min(1),
  projectType: z.string().optional(),
  country: z.string().optional(),
  city: z.string().optional(),
  market: z.string().optional(),
  website: z.string().url().optional().or(z.literal("")),
  socialLinks: z.array(z.string().url()).optional(),
  products: z.array(z.string()).optional(),
  services: z.array(z.string()).optional(),
  mainProducts: z.array(z.string()).optional(),
  priceRange: z.string().optional(),
  usps: z.array(z.string()).optional(),
  problem: z.string().optional(),
  audienceAgeRange: z.string().optional(),
  audienceGender: z.string().optional(),
  audienceLocation: z.string().optional(),
  audienceIncome: z.string().optional(),
  audienceInterests: z.array(z.string()).optional(),
  audienceBehavior: z.string().optional(),
  audienceNeeds: z.array(z.string()).optional(),
  audienceConcerns: z.array(z.string()).optional(),
  audienceMotivations: z.array(z.string()).optional(),
  personality: z.object({
    luxurious: z.number().min(1).max(5).optional(),
    modern: z.number().min(1).max(5).optional(),
    bold: z.number().min(1).max(5).optional(),
    friendly: z.number().min(1).max(5).optional(),
    formal: z.number().min(1).max(5).optional(),
    simple: z.number().min(1).max(5).optional(),
    innovative: z.number().min(1).max(5).optional(),
    technical: z.number().min(1).max(5).optional(),
    natural: z.number().min(1).max(5).optional(),
    heritage: z.number().min(1).max(5).optional(),
    playful: z.number().min(1).max(5).optional(),
    calm: z.number().min(1).max(5).optional(),
  }).partial().optional(),
  visualPreferences: z.array(z.string()).optional(),
  preferredColors: z.array(z.string()).optional(),
  forbiddenColors: z.array(z.string()).optional(),
  preferredFonts: z.array(z.string()).optional(),
  forbiddenFonts: z.array(z.string()).optional(),
  likedLogos: z.array(z.string()).optional(),
  dislikedLogos: z.array(z.string()).optional(),
  referenceFiles: z.array(z.object({ url: z.string(), name: z.string() })).optional(),
  competitorLinks: z.array(z.string().url()).optional(),
  additionalNotes: z.string().optional(),
});
export type BrandBriefInput = z.infer<typeof BrandBriefInputSchema>;
